# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

use_frameworks!

def pods
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'RxGesture'
end

target 'Booster' do
  pods
end

target 'StatisticsTests' do
  pods
  pod 'RxTest'
  pod 'RxBlocking'
end

target 'TrackingProgressTests' do
  pods
  pod 'RxTest'
  pod 'RxBlocking'
end
