# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Booster' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Booster

  pod 'SwiftLint'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSource'
  pod 'RxGesture'

end

target 'StatisticsTests' do
  use_frameworks!
  
  pod 'RxBlocking'
  pod 'RxTest'
end 

target 'TrackingProgressTests' do 
  use_frameworks!
  
  pod 'RxBlocking'
  pod 'RxTest'
end
