# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Booster' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Booster

  pod 'SwiftLint'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'RxGesture'

end
